POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/df34f55c-e4bf-46d0-af7d-4a761c56493d